# Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRooms
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Sala de teste"
}

###

@roomId = {{getRooms.response.body.$.[0].id}}

###

# Get Rooms Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Room
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "Qual é a pergunta?",
}

###